spring:
  application:
    name: shiftly
  profiles:
    default: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  cors:
    allowed-origins:
      - http://localhost:5173
